services:
  - type: web
    name: gitfolio-backend
    env: node
    buildCommand: npm install
    startCommand: node server.cjs
    envVars:
      - key: PORT
        value: 5000
      - key: GITHUB_TOKEN
        value: ${GITHUB_TOKEN} # This should reference an environment variable, not the actual token
      - key: NODE_ENV
        value: production
      - key: FRONTEND_URL
        value: https://git-folio-frontend-c1gx-jze26qjou-ishikajais27s-projects.vercel.app/
